-- READ-ONLY ANALYSIS — this file is not a migration and applies no schema change.
--
-- Phase A cutover: NOT DEPLOYED YET. Replace this line with the UTC deployment
-- timestamp before interpreting a mixed old/new window. Events cannot be
-- backfilled, so an undated cutover makes every cross-boundary number a guess.
--
-- Owner this round: Claude (see TRACKINGDISCUSSION.md § Claude orchestration,
-- file ownership table O3). GPT owns the TypeScript side of the same contract;
-- do not edit this file from that side.
--
-- Contract notes (frozen interface §O2):
--   * I1: path is pathname-only for EVERY event type after the cutover. Old rows
--     may still carry a query. Nothing here may assume a query exists.
--   * I5: acquisition enum value is `unattributed`, never `direct`. The browser
--     cannot separate genuine direct traffic from referrer-stripped WhatsApp,
--     Facebook or privacy browsers, so the honest name is the absence of a
--     signal. NEVER compute a channel's share as (total - unattributed).
--   * I8: contact `rail` is required-present but NULLABLE. 78.8% of listing_open
--     rows legitimately carry rail:null (deep links and the plain feed). A
--     non-null-rail gate is unsatisfiable; gate on key presence instead.
--   * I9: every conversion metric excludes sale listings under $5,000. That
--     group took 13.5% of sale contacts in 24h and is an ingestion defect, not
--     demand. Including it measures the bug.
--   * listing_open means successful detail client hydration after fetch. It is
--     not proof of an intentional card click, and it cannot observe a detail
--     page that never hydrated.
--   * I10: do not quote the 0.197 opens/contacts Spearman figure — 93.3% of sale
--     listings tie at zero contacts, so the statistic is tie-dominated.


-- ---------------------------------------------------------------------------
-- 1. Acquisition mix across the compatibility boundary.
--
-- New rows carry bounded acquisition meta. Old rows can only be recovered as far
-- as a click id in the path; their ABSENCE proves nothing, because referrer_host
-- was never recorded. Those rows are `unknown_legacy` and must never be folded
-- into `unattributed` — that would invent a trend across the cutover.
-- ---------------------------------------------------------------------------
select
  case
    when meta ? 'acq_source' then meta ->> 'acq_source'
    when path ilike '%fbclid=%' then 'facebook_legacy'
    when path ilike '%gclid=%'  then 'google_legacy'
    else 'unknown_legacy'
  end as acquisition,
  case
    when meta ? 'paid_click' then (meta ->> 'paid_click')::boolean
    when path ilike '%fbclid=%' or path ilike '%gclid=%' then true
    else null
  end as paid_click,
  count(*)                  as starts,
  count(distinct session_id) as sessions
from public.site_events
where event_type = 'session_start'
  and coalesce(meta ->> 'env', '') <> 'preview'
group by 1, 2
order by starts desc;


-- ---------------------------------------------------------------------------
-- 2. Contact attribution.
--
-- Legacy rows keep NULL rail/sort/deal. Never fill them from a later event in
-- the same session — that invents chronology (trap 23).
-- ---------------------------------------------------------------------------
select
  event_type,
  meta ->> 'surface' as surface,
  meta ->> 'rail'    as rail,
  meta ->> 'sort'    as sort,
  meta ->> 'deal'    as deal,
  count(*)                   as contacts,
  count(distinct session_id) as sessions
from public.site_events
where event_type in ('call_tap', 'wa_tap')
  and coalesce(meta ->> 'env', '') <> 'preview'
group by 1, 2, 3, 4, 5
order by contacts desc;


-- ---------------------------------------------------------------------------
-- 3. POST-SHIP GATE — contact attribution completeness (I8).
--
-- `rail` is gated on KEY PRESENCE, not on being non-null. `sort`/`deal` resolve
-- at 100% today (1,706/1,706 opens) and are gated at >=99%.
-- Read after the cutover only; rows before it are expected to fail by design.
-- ---------------------------------------------------------------------------
select
  count(*)                                                             as contacts,
  round(100.0 * count(*) filter (where meta ? 'surface')   / count(*), 1) as pct_surface,
  round(100.0 * count(*) filter (where meta ? 'rail')      / count(*), 1) as pct_rail_key_present,
  round(100.0 * count(*) filter (where meta ->> 'rail' is not null) / count(*), 1)
                                                                       as pct_rail_non_null_fyi,
  round(100.0 * count(*) filter (where meta ? 'sort')      / count(*), 1) as pct_sort,
  round(100.0 * count(*) filter (where meta ? 'deal')      / count(*), 1) as pct_deal,
  -- I1 must hold for every type, not only session_start.
  count(*) filter (where path like '%?%' or path like '%#%')            as contacts_with_query_in_path
from public.site_events
where event_type in ('call_tap', 'wa_tap')
  and coalesce(meta ->> 'env', '') <> 'preview'
  and created_at >= now() - interval '24 hours';


-- ---------------------------------------------------------------------------
-- 4. POST-SHIP GATE — I1 path privacy, ALL event types.
--
-- The pre-Phase-A failure this gate exists to catch: sanitizing only
-- session_start left 111 of 220 live click ids in place, 87/day of them on
-- filter_apply. Any non-zero number here after the cutover is a regression.
-- ---------------------------------------------------------------------------
select
  event_type,
  count(*)                                          as rows_24h,
  count(*) filter (where path like '%?%' or path like '%#%') as with_query,
  count(*) filter (where path ilike '%fbclid%'
                      or path ilike '%gclid%')      as with_click_id
from public.site_events
where created_at >= now() - interval '24 hours'
group by 1
order by with_click_id desc, rows_24h desc;


-- ---------------------------------------------------------------------------
-- 5. FROZEN detail-entry gap query.
--
-- This board has quoted 23%, 11.2% and 22.6% for the same thing. The spread is
-- definition sensitivity, not movement, so the definition is frozen here and the
-- number is whatever this query returns. Do not re-cut it per analysis.
--
-- Definition, fixed:
--   * session whose session_start carries meta.entry LIKE '/listing/%'
--     (entry has always been pathname-only, so this works across the cutover)
--   * started at least 10 minutes before the query bound (maturity rule) so a
--     session still in flight cannot count as a failure
--   * the listing is still visible in listings_public (a removed listing
--     explains a missing open without any client defect)
--   * no listing_open for THAT listing in the SAME session
--
-- ⚠️ A gap here is NOT "a missing open click". listing_open fires on successful
-- hydration, so this measures hydration failure + bounce + error together.
-- Splitting them needs server/host evidence, not another client event.
-- ---------------------------------------------------------------------------
with starts as (
  select
    e.session_id,
    e.created_at,
    nullif(regexp_replace(e.meta ->> 'entry', '^/listing/(\d+).*$', '\1'), e.meta ->> 'entry')::bigint
      as entry_listing_id
  from public.site_events e
  where e.event_type = 'session_start'
    and e.meta ->> 'entry' like '/listing/%'
    and coalesce(e.meta ->> 'env', '') <> 'preview'
    and e.created_at >= now() - interval '24 hours'
    and e.created_at <  now() - interval '10 minutes'   -- maturity rule
),
visible as (
  select s.*
  from starts s
  join public.listings_public lp on lp.id = s.entry_listing_id
  where s.entry_listing_id is not null
),
opened as (
  select v.session_id, v.entry_listing_id,
         exists (
           select 1
           from public.site_events o
           where o.session_id = v.session_id
             and o.event_type = 'listing_open'
             and o.listing_id = v.entry_listing_id
         ) as did_open
  from visible v
)
select
  count(*)                                  as mature_detail_entries,
  count(*) filter (where not did_open)      as without_listing_open,
  round(100.0 * count(*) filter (where not did_open) / nullif(count(*), 0), 1)
                                            as pct_gap
from opened;


-- ---------------------------------------------------------------------------
-- 6. Conversion by contact surface — WITH the I9 exclusion.
--
-- Sub-$5k "sale" rows are mislabelled rentals. listings_public.price_sort
-- already nulls them for display, but they still rank in the feed and still
-- absorb real intent, so they must be excluded here or the pack reports the
-- ingestion bug as demand. `invalid_inventory` is reported separately rather
-- than silently dropped — a number that disappears is a number nobody fixes.
-- ---------------------------------------------------------------------------
with ev as (
  select e.event_type, e.listing_id, e.session_id, l.deal_type, l.price_usd
  from public.site_events e
  join public.listings l on l.id = e.listing_id
  where e.created_at >= now() - interval '24 hours'
    and e.event_type in ('listing_open', 'call_tap', 'wa_tap')
    and e.listing_id is not null
    and coalesce(e.meta ->> 'env', '') <> 'preview'
),
classed as (
  select *,
    case
      when deal_type = 'sale' and price_usd < 5000 then 'invalid_inventory'
      else deal_type
    end as segment
  from ev
)
select
  segment,
  count(distinct session_id) filter (where event_type = 'listing_open')            as openers,
  count(distinct session_id) filter (where event_type in ('call_tap', 'wa_tap'))   as contacters,
  round(
    100.0 * count(distinct session_id) filter (where event_type in ('call_tap', 'wa_tap'))
          / nullif(count(distinct session_id) filter (where event_type = 'listing_open'), 0)
  , 1)                                                                            as contact_rate_pct
from classed
group by 1
order by openers desc;


-- ---------------------------------------------------------------------------
-- 7. Comparison depth vs contact — the strongest live association.
--
-- Kept because it is the one relationship that has replicated across days, and
-- because it is what Phase B's `paginate` is meant to explain. Same I9
-- exclusion applies.
--
-- ⚠️ The `0` depth bucket is an artifact, not a 100%-converting segment: it is
-- sessions that contacted while their listing_open fell outside the window (or
-- called straight from a feed card). Measured at 3 sessions in a 24h run. Read
-- the 1 / 2-3 / 4-6 / 7+ buckets; never quote `0`.
-- ---------------------------------------------------------------------------
with ev as (
  select e.event_type, e.session_id, e.listing_id
  from public.site_events e
  join public.listings l on l.id = e.listing_id
  where e.created_at >= now() - interval '24 hours'
    and e.event_type in ('listing_open', 'call_tap', 'wa_tap')
    and e.listing_id is not null
    and coalesce(e.meta ->> 'env', '') <> 'preview'
    and not (l.deal_type = 'sale' and l.price_usd < 5000)   -- I9
),
sess as (
  select session_id,
         count(distinct listing_id) filter (where event_type = 'listing_open') as listings_opened,
         count(*) filter (where event_type in ('call_tap', 'wa_tap')) > 0      as contacted
  from ev
  group by 1
)
select
  case
    when listings_opened = 0 then '0'
    when listings_opened = 1 then '1'
    when listings_opened between 2 and 3 then '2-3'
    when listings_opened between 4 and 6 then '4-6'
    else '7+'
  end as depth,
  count(*)                                as sessions,
  count(*) filter (where contacted)       as contacted_sessions,
  round(100.0 * count(*) filter (where contacted) / count(*), 1) as contact_rate_pct
from sess
group by 1
order by min(listings_opened);
